use std::time::Duration;

use anyhow::{anyhow, Context};
use reqwest::blocking::Client;
use serde::{Deserialize, Serialize};

/// Configuration for an AI summary provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiConfig {
    pub enabled: bool,
    pub provider: String,
    pub base_url: String,
    pub api_key: String,
    pub model: String,
}

impl Default for AiConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            provider: "deepseek".to_string(),
            base_url: "https://api.deepseek.com/v1".to_string(),
            api_key: String::new(),
            model: "deepseek-chat".to_string(),
        }
    }
}

/// Result from a test_connection call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectionTestResult {
    pub success: bool,
    pub message: String,
    pub models: Vec<String>,
}

/// A summary block generated by an AI provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedSummary {
    pub block_start: String,
    pub block_end: String,
    pub main_focus: String,
    pub apps_projects: Vec<String>,
    pub context_switches: usize,
    pub total_focus_minutes: i64,
    pub productivity_notes: Vec<String>,
    pub plain_english_summary: String,
    pub model_used: String,
}

/// The trait each provider must implement.
pub trait SummaryProvider: Send + Sync {
    fn test_connection(&self) -> anyhow::Result<ConnectionTestResult>;
    fn generate_summary(&self, prompt: &str) -> anyhow::Result<GeneratedSummary>;
}

// ---------------------------------------------------------------------------
// LM Studio provider
// ---------------------------------------------------------------------------

pub struct LmStudioProvider {
    client: Client,
    config: AiConfig,
}

impl LmStudioProvider {
    pub fn new(config: AiConfig) -> Self {
        let client = Client::builder()
            .timeout(Duration::from_secs(30))
            .build()
            .expect("reqwest client");
        Self { client, config }
    }
}

impl SummaryProvider for LmStudioProvider {
    fn test_connection(&self) -> anyhow::Result<ConnectionTestResult> {
        let url = format!("{}/models", self.config.base_url.trim_end_matches('/'));
        let resp = self
            .client
            .get(&url)
            .send()
            .context("LM Studio connection refused")?;
        if !resp.status().is_success() {
            return Ok(ConnectionTestResult {
                success: false,
                message: format!("HTTP {}", resp.status()),
                models: vec![],
            });
        }
        let body: serde_json::Value = resp.json().context("invalid LM Studio response")?;
        let models: Vec<_> = body["data"]
            .as_array()
            .map(|arr| {
                arr.iter()
                    .filter_map(|m| m["id"].as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();
        Ok(ConnectionTestResult {
            success: !models.is_empty(),
            message: if models.is_empty() {
                "Connected but no models loaded".to_string()
            } else {
                format!("Connected — {} model(s) loaded", models.len())
            },
            models,
        })
    }

    fn generate_summary(&self, prompt: &str) -> anyhow::Result<GeneratedSummary> {
        let url = format!("{}/chat/completions", self.config.base_url.trim_end_matches('/'));
        let model = if self.config.model.is_empty() {
            "local-model"
        } else {
            &self.config.model
        };
        let body = serde_json::json!({
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a productivity assistant. Analyze the activity data and return ONLY valid JSON without markdown fences or commentary."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.3,
            "max_tokens": 1024,
        });
        let resp: serde_json::Value = self
            .client
            .post(&url)
            .json(&body)
            .send()
            .context("LM Studio request failed")?
            .json()
            .context("LM Studio response parse failed")?;
        let content = resp["choices"][0]["message"]["content"]
            .as_str()
            .ok_or_else(|| anyhow!("LM Studio returned empty response"))?;
        parse_summary_response(content, model)
    }
}

// ---------------------------------------------------------------------------
// Ollama provider
// ---------------------------------------------------------------------------

pub struct OllamaProvider {
    client: Client,
    config: AiConfig,
}

impl OllamaProvider {
    pub fn new(config: AiConfig) -> Self {
        let client = Client::builder()
            .timeout(Duration::from_secs(30))
            .build()
            .expect("reqwest client");
        Self { client, config }
    }
}

impl SummaryProvider for OllamaProvider {
    fn test_connection(&self) -> anyhow::Result<ConnectionTestResult> {
        let url = format!("{}/api/tags", self.config.base_url.trim_end_matches('/'));
        let resp = self
            .client
            .get(&url)
            .send()
            .context("Ollama connection refused")?;
        let body: serde_json::Value = resp.json().context("invalid Ollama response")?;
        let models: Vec<_> = body["models"]
            .as_array()
            .map(|arr| {
                arr.iter()
                    .filter_map(|m| m["name"].as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();
        Ok(ConnectionTestResult {
            success: !models.is_empty(),
            message: if models.is_empty() {
                "Connected but no models loaded".to_string()
            } else {
                format!("Connected — {} model(s) loaded", models.len())
            },
            models,
        })
    }

    fn generate_summary(&self, prompt: &str) -> anyhow::Result<GeneratedSummary> {
        let url = format!("{}/api/chat", self.config.base_url.trim_end_matches('/'));
        let model = if self.config.model.is_empty() {
            "llama3.2"
        } else {
            &self.config.model
        };
        let body = serde_json::json!({
            "model": model,
            "messages": [
                {"role": "system", "content": "You are a productivity assistant. Return ONLY valid JSON without markdown fences."},
                {"role": "user", "content": prompt}
            ],
            "stream": false,
            "options": {"temperature": 0.3, "num_predict": 1024}
        });
        let resp: serde_json::Value = self
            .client
            .post(&url)
            .json(&body)
            .send()
            .context("Ollama request failed")?
            .json()
            .context("Ollama response parse failed")?;
        let content = resp["message"]["content"]
            .as_str()
            .ok_or_else(|| anyhow!("Ollama returned empty response"))?;
        parse_summary_response(content, model)
    }
}

// ---------------------------------------------------------------------------
// OpenAI-compatible provider (scaffold — disabled by default)
// ---------------------------------------------------------------------------

pub struct OpenAiCompatibleProvider {
    client: Client,
    config: AiConfig,
}

impl OpenAiCompatibleProvider {
    pub fn new(config: AiConfig) -> Self {
        let client = Client::builder()
            .timeout(Duration::from_secs(30))
            .build()
            .expect("reqwest client");
        Self { client, config }
    }
}

impl SummaryProvider for OpenAiCompatibleProvider {
    fn test_connection(&self) -> anyhow::Result<ConnectionTestResult> {
        let url = format!("{}/models", self.config.base_url.trim_end_matches('/'));
        let mut req = self.client.get(&url);
        if !self.config.api_key.is_empty() {
            req = req.header("Authorization", format!("Bearer {}", self.config.api_key));
        }
        let resp = req.send().context("OpenAI-compatible connection refused")?;
        if !resp.status().is_success() {
            return Ok(ConnectionTestResult {
                success: false,
                message: format!("HTTP {}", resp.status()),
                models: vec![],
            });
        }
        let body: serde_json::Value = resp.json()?;
        let models: Vec<_> = body["data"]
            .as_array()
            .map(|arr| {
                arr.iter()
                    .filter_map(|m| m["id"].as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();
        Ok(ConnectionTestResult {
            success: !models.is_empty(),
            message: if models.is_empty() {
                "Connected but no models available".to_string()
            } else {
                format!("Connected — {} model(s) available", models.len())
            },
            models,
        })
    }

    fn generate_summary(&self, prompt: &str) -> anyhow::Result<GeneratedSummary> {
        let url = format!("{}/chat/completions", self.config.base_url.trim_end_matches('/'));
        let model = if self.config.model.is_empty() {
            "gpt-4o-mini"
        } else {
            &self.config.model
        };
        let mut req = self
            .client
            .post(&url)
            .json(&serde_json::json!({
                "model": model,
                "messages": [
                    {"role": "system", "content": "You are a productivity assistant. Return ONLY valid JSON without markdown fences."},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.3,
                "max_tokens": 1024,
            }));
        if !self.config.api_key.is_empty() {
            req = req.header("Authorization", format!("Bearer {}", self.config.api_key));
        }
        let resp: serde_json::Value = req.send()?.json()?;
        let content = resp["choices"][0]["message"]["content"]
            .as_str()
            .ok_or_else(|| anyhow!("OpenAI-compatible returned empty response"))?;
        parse_summary_response(content, model)
    }
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

pub fn create_provider(config: &AiConfig) -> anyhow::Result<Box<dyn SummaryProvider>> {
    match config.provider.as_str() {
        "lm_studio" => Ok(Box::new(LmStudioProvider::new(config.clone()))),
        "ollama" => Ok(Box::new(OllamaProvider::new(config.clone()))),
        "deepseek" | "openai_compatible" => Ok(Box::new(OpenAiCompatibleProvider::new(config.clone()))),
        other => Err(anyhow!("Unknown provider: {other}")),
    }
}

// ---------------------------------------------------------------------------
// Response parser
// ---------------------------------------------------------------------------

fn parse_summary_response(content: &str, model: &str) -> anyhow::Result<GeneratedSummary> {
    // Strip markdown fences if present
    let cleaned = content
        .trim()
        .strip_prefix("```json")
        .or_else(|| content.trim().strip_prefix("```"))
        .and_then(|s| s.strip_suffix("```"))
        .map(|s| s.trim())
        .unwrap_or(content.trim());

    let val: serde_json::Value =
        serde_json::from_str(cleaned).context("AI returned invalid JSON — check model output")?;

    Ok(GeneratedSummary {
        block_start: val["block_start"].as_str().unwrap_or("").to_string(),
        block_end: val["block_end"].as_str().unwrap_or("").to_string(),
        main_focus: val["main_focus"].as_str().unwrap_or("Work session").to_string(),
        apps_projects: val["apps_projects"]
            .as_array()
            .map(|a| a.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
            .unwrap_or_default(),
        context_switches: val["context_switches"].as_u64().unwrap_or(0) as usize,
        total_focus_minutes: val["total_focus_minutes"].as_i64().unwrap_or(0),
        productivity_notes: val["productivity_notes"]
            .as_array()
            .map(|a| a.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
            .unwrap_or_default(),
        plain_english_summary: val["plain_english_summary"]
            .as_str()
            .unwrap_or("No summary generated.")
            .to_string(),
        model_used: model.to_string(),
    })
}
